config/routes.rb
Rails.application.routes.draw do
  

  resources :users do
    resources :goals, only: [:new, :create, :index]
  end
  
  resources :goals, only: [:show, :destroy, :edit] do
    member { patch "complete" => "goals#complete" }
  end
  resource :session
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  public     :boolean          not null
#  completed  :boolean          not null
#  title      :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Goal < ActiveRecord::Base
  validates :user_id, :title, presence: true
  validates :completed, :public, inclusion: [true, false]
  
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  username   :string(255)
#  password   :string(255)
#  token      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  validates :username, :password, presence: true
  validates :username, uniqueness: true
  validates :password, length: {minimum: 6}
  
  def set_token
    self.token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.token
  end
  
  has_many :goals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  
  helper_method :current_user
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
  
  def login_user(user)
    session[:token] = user.set_token
    @current_user = user
  end
  
  def log_out
    current_user.try(:set_token)
    session[:token] = nil
  end
  
  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_token(session[:token])
  end
  
  def require_log_in
    redirect_to new_session_url unless !!current_user
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
  end
  
  def create
    @goal = Goal.new(goal_params)
    @goal.public ||= false # default on table?
    @goal.completed ||= false ## default on table?
    @goal.user_id = params[:user_id]
   
    
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end
  
  def index
    @goals = Goal.all
  end
  
  def show
    @goal = Goal.find(params[:id])
    
    if @goal.public || current_user.id == @goal.user_id
      render 'show'
    else
      flash.now[:errors] = ["Not authorized to view goal"]
      redirect_to user_goals_url(current_user)
    end
  end
  
  def complete
    @goal = Goal.find(params[:id])
    @goal.completed = true
    @goal.save!
    
    redirect_to goal_url(@goal)
  end

  private
  
  def goal_params
    params.require(:goal).permit(:title, :completed, :public)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    redirect_to user_url(current_user) if current_user
  end
  
  def create
    @user = User.find_by(user_params)
    if @user
      login_user(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :require_log_in, except: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def new
    redirect_to user_url(current_user) if current_user
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      login_user(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<ul>
Your Goals
<% @goals.each do |goal| %>
<% if goal.user_id == current_user.id %>
<li><%= link_to goal.title, goal_url(goal) %></li>
<% end %>
<% end %>
</ul>

<ul>
Public Goals
<% @goals.each do |goal| %>
<% if goal.user_id != current_user.id && goal.public%>
<li><%= link_to goal.title, goal_url(goal) %></li>
<% end %>
<% end %>
</ul>

app/views/goals/new.html.erb
Create Goal
<form action="<%= user_goals_url(current_user.id) %>" method="post" accept-charset="utf-8">
  
  <label for="title">Title</label><input type="text" name="goal[title]" value="" id="title">
  
<label for="public">Public</label>
  <input type="checkbox" name="goal[public]" value="true" id="public">

  <p><input type="submit" value="Create Goal"></p>
</form>

app/views/goals/show.html.erb
<%= @goal.title %><br>
Public: <%= @goal.public %><br>
Completed: <%= @goal.completed %>

<% if current_user.id == @goal.user_id %>

<%= button_to "Completed", complete_goal_url(@goal), method: :patch %>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cheers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<% if current_user %>
  <%= "Welcome #{current_user.username}" %>
  <%= button_to "Log Out", session_url, method: :delete %>
  <%= link_to "Create Goal", new_user_goal_url(current_user) %>
  <%= link_to "Goals", user_goals_url(current_user) %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign up", new_user_url %>
<% end %>
  
<%= flash[:errors] if flash[:errors] %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
Sign Up
<form action="<%= users_url %>" method="post">
  <label for="username">Username</label><input type="text" name="user[username]" value="" id="username">
  
  <label for="password">Password</label><input type="text" name="user[password]" value="" id="password">
  
  

  <p><input type="submit" value="Create User"></p>
</form>

app/views/users/show.html.erb
<%= @user.username %>